### ISSUE TITLE
mount field to process new data assets in a pipeline

### ISSUE THREAD

**Issue by arielleleon** [AllenNeuralDynamics/aind-data-transfer-service#111]
**Is your feature request related to a problem? Please describe.**
I cannot specify a mount point for a capsule in the current architecture. This is required to trigger a pipeline with a new data asset.

**Describe the solution you'd like**
I would like a mount field to the BasicJobUploadConfig so that transfer-service can specify a mount point when a pipeline is processed.

**Comment by dyf** [comment]
@arielleleon @jtyoung84 I'm wondering if we want also to just have a library of configurations that know how to set mount points and other properties by default.  For example the `ecephys` cares about two mount points (one for the data, one for the noise classifier model). The `single-plane-ophys` and `multiplane-ophys` pipelines likewise would have their own.  

Concern with this is that I think the trigger capsule needs to know about this as well.

**Comment by arielleleon** [comment]
@dyf @jtyoung84 I'm fine with a default configuration for platform / modality. But do we need to care about the trigger capsule anymore? Looks like the aind-data-transfer basic-job can take in any capsule id

**Comment by dyf** [comment]
@arielleleon If a scientist wants to trigger reprocessing without re-uploading themselves, one way to do that is to use the trigger capsule app panel. It is (debatably) convenient to be able to do this within Code Ocean rather than learning to use the API.

**Comment by jtyoung84** [comment]
@arielleleon Currently, the trigger capsule is run as default. It registers a data, runs a pipeline, monitors the pipeline, and captures the results once the pipeline is finished. We can add update the BasicUploadJobConfigs class to handle other cases, although I'd like to keep things backwards compatible as much as possible.

@dyf I discussed this Alessio. I think it should be fine having defaults in the trigger capsule repo itself. I'm probably fine with having the defaults checked in the repo, but we can pull them from a database if needed.
